// ── Trip configuration ──────────────────────────────────────────────
// Times tweaked slightly from the original plan for realistic walking:
// the two fixed bookings are King's College Chapel 14:00 and punting 15:45
// (check-in by 15:30 at Jesus Green).

const TRIP = {
  date: '2026-06-13', // tomorrow
  title: 'A Day in Cambridge',
  syncId: 'cam-0d80f8ea2cd8', // shared Firestore path — both phones see the same photos/notes
};

// Shared backend (Firestore free tier; rules only open the trip path above)
const FIREBASE_CONFIG = {
  apiKey: 'AIzaSyCGyP10WWpGVQCCiH8_Tlmn2IgXpyMDuEg',
  authDomain: 'cambridge-day-2026.firebaseapp.com',
  projectId: 'cambridge-day-2026',
  appId: '1:925410625884:web:e983e8e09ec46c32a3d999',
};

// Each stop has a hero photo at images/<id>.jpg (bundled, works offline).
// Credits for the freely-licensed photos (Wikimedia Commons).
const IMAGE_CREDITS = {
  station: 'mattbuck · CC BY-SA 4.0',
  fitzwilliam: 'Wikimedia Commons · CC BY-SA 2.0',
  fitzbillies: 'Wikimedia Commons · CC BY-SA 2.0',
  'bridge-clock': 'TheKaphox · CC0',
  kings: 'Dmitry Tonkonog · CC BY-SA 3.0',
  'walk-river': 'M J Richardson · CC BY-SA 2.0',
  punting: 'Colin Smith · CC BY-SA 2.0',
  bookshop: 'Jeff Gogarty · CC BY-SA 2.0',
  eagle: 'Andy Oxford · CC BY-SA 3.0',
  dishoom: 'Hans Wolff · Public domain',
  gelato: 'Smb1001 · CC BY-SA 4.0',
};

const STOPS = [
  {
    id: 'station',
    tease: 'bring comfy shoes',
    walkLine: '',
    nowLine: 'and so it begins',
    place: 'Cambridge Station',
    emoji: '🚉',
    name: 'Arrive at Cambridge Station',
    start: '11:00', end: '11:25',
    walk: null,
    booked: false,
    mapQuery: 'Cambridge Railway Station, Station Road, Cambridge, UK',
    desc: 'The day begins! It’s a pleasant 25-minute walk into town — straight up Station Road, then Hills Road becomes Regent Street becomes Trumpington Street, and the Fitzwilliam appears on your left like a Greek temple.',
    tips: [
      'Grab water for the walk — the day is mostly on foot.',
      'Loos at the station are easier than hunting for one in town.',
      'If it’s raining, the Citi 1/3 buses or a taxi get you to the museum in ~8 minutes.',
    ],
  },
  {
    id: 'fitzwilliam',
    tease: 'five centuries of treasure, free entry',
    walkLine: 'a straight stroll up Trumpington Street',
    nowLine: 'eyes up in the entrance hall',
    place: 'the Fitzwilliam',
    emoji: '🏛️',
    name: 'The Fitzwilliam Museum',
    start: '11:25', end: '12:30',
    walk: '25 min walk from the station',
    booked: false,
    mapQuery: 'The Fitzwilliam Museum, Trumpington Street, Cambridge, UK',
    website: 'https://fitzmuseum.cam.ac.uk',
    desc: 'One of the best free museums in the country — a treasure house of Titians, Monets, Egyptian sarcophagi and illuminated manuscripts behind a jaw-dropping portico.',
    tips: [
      'Entry is free — no ticket needed. Large bags go in the cloakroom.',
      'With ~an hour, cherry-pick: Egyptian galleries downstairs, then Impressionists (Gallery 5) and the armoury.',
      'Look up in the entrance hall — the ceiling is half the show.',
      'Don’t exhaust yourselves: one hour of highlights beats three hours of duty.',
    ],
  },
  {
    id: 'fitzbillies',
    tease: 'the Chelsea buns are calling',
    walkLine: 'follow the smell of cinnamon',
    nowLine: 'one bun now, one boxed for later',
    place: 'Fitzbillies',
    emoji: '🥐',
    name: 'Lunch at Fitzbillies',
    start: '12:30', end: '13:15',
    walk: '2 min walk',
    booked: false,
    mapQuery: 'Fitzbillies, 51-52 Trumpington Street, Cambridge, UK',
    website: 'https://www.fitzbillies.com',
    desc: 'A Cambridge institution since 1920, two minutes up the road. Famous for the stickiest Chelsea buns in existence — students have been posting them home for a century.',
    tips: [
      'The Chelsea bun is non-negotiable. Get one to share now and one boxed for later.',
      'If the café queue is long, the takeaway counter moves much faster.',
      'Smoked salmon & scrambled eggs and the sausage roll are the savoury heroes.',
    ],
  },
  {
    id: 'bridge-clock',
    tease: 'a wooden bridge and a time-eating monster',
    walkLine: 'two photo stops on the way to King’s',
    nowLine: 'find the grasshopper eating time',
    place: 'the Mathematical Bridge',
    emoji: '🌉',
    name: 'Mathematical Bridge & Corpus Clock',
    start: '13:15', end: '13:50',
    walk: '8 min walk',
    booked: false,
    mapQuery: 'Mathematical Bridge, Silver Street, Cambridge, UK',
    desc: 'A lazy wander north. Turn down Silver Street for the best view of the Mathematical Bridge (Queens’ College, 1749), then double back up King’s Parade to find the gold, grasshopper-topped Corpus Clock.',
    tips: [
      'Best photo of the bridge: from Silver Street bridge, looking down the river.',
      'Myth-bust to impress: no, it wasn’t built by Newton, and yes, it does use bolts.',
      'The Corpus Clock’s monster is the “Chronophage” — time-eater. It’s only accurate once every five minutes, on purpose.',
      'You’re aiming to be at King’s front gate by ~13:50 for the 14:00 tour.',
    ],
  },
  {
    id: 'kings',
    tease: 'the big one — tour at 2pm sharp',
    walkLine: 'tickets ready — entrance on King’s Parade',
    nowLine: 'the ceiling is the masterpiece',
    place: 'King’s College',
    emoji: '⛪',
    name: 'King’s College Chapel',
    start: '14:00', end: '15:15',
    walk: '5 min walk',
    booked: true,
    bookedLabel: 'Booked · 14:00',
    hasTickets: true,
    mapQuery: "King's College Chapel, King's Parade, Cambridge, UK",
    website: 'https://www.kings.cam.ac.uk/visit',
    desc: 'The big one. Five centuries of kings, the largest fan-vaulted ceiling in the world, and Rubens’ Adoration of the Magi behind the altar. Your tour is booked for 2pm sharp.',
    tips: [
      'Be at the visitor entrance ~10 minutes early with your ticket ready (add it below!).',
      'Walk the full length slowly and keep looking up — the fan vaulting is the masterpiece.',
      'Spot the Tudor graffiti: carved initials of 16th-century stonemasons near the side chapels.',
      'The lawn-and-river view from the Backs side is the classic postcard shot.',
    ],
  },
  {
    id: 'walk-river',
    tease: 'check in by 3:30 — look for the orange umbrella',
    walkLine: 'head for Jesus Green and the orange umbrella',
    nowLine: 'checked in? loos are on the green',
    place: 'the punting check-in',
    emoji: '🚶',
    name: 'Walk to the river & check in',
    start: '15:15', end: '15:45',
    walk: '15 min walk',
    booked: false,
    mapQuery: 'Traditional Punting Company, Thompsons Lane, Cambridge CB5 8AQ, UK',
    desc: 'Stroll up Trinity Street and Bridge Street to Jesus Green. The Traditional Punting Company’s landing stage is on Thompsons Lane, on the corner of Jesus Green behind La Mimosa — look for the orange umbrella.',
    tips: [
      'Leave King’s by 15:10-15:15 — check-in is by 15:30.',
      'Find the orange umbrella, check in with the cashier, then wait by the meeting-point sign next to the Jesus Green tennis courts.',
      'Lost? Call them on 01223 782306.',
      'Quick loo stop: there are public toilets on Jesus Green.',
    ],
  },
  {
    id: 'punting',
    tease: 'the most romantic hour of the day',
    walkLine: 'the river is waiting',
    nowLine: 'phones out for the Bridge of Sighs',
    place: 'the riverbank',
    emoji: '🛶',
    name: 'Punting on the Cam',
    start: '15:45', end: '16:45',
    walk: null,
    booked: true,
    bookedLabel: 'Booked · 15:45 (check in 15:30)',
    hasTickets: true,
    mapQuery: 'Traditional Punting Company, Thompsons Lane, Cambridge CB5 8AQ, UK',
    website: 'https://traditionalpuntingcompany.com',
    desc: 'The most romantic hour of the day — gliding past the Backs while your chauffeur does the hard work. You’ll drift under the Bridge of Sighs and past Trinity, King’s and Queens’ from their best angle.',
    tips: [
      'Sit facing each other at the front for the best photos (and legroom).',
      'The Bridge of Sighs shot is the keeper — phones out as you approach St John’s.',
      'Ask your chauffeur questions — the good ones are full of college gossip from 800 years of history.',
      'It’s cooler on the water — a light layer is a good idea.',
    ],
  },
  {
    id: 'bookshop',
    tease: 'ghosts, old books and market stalls',
    walkLine: 'bookshop first — it closes early',
    nowLine: 'buy each other a secret book',
    place: 'the Haunted Bookshop',
    emoji: '📚',
    name: 'Haunted Bookshop & Market Square',
    start: '16:45', end: '17:30',
    walk: '12 min walk',
    booked: false,
    mapQuery: 'The Haunted Bookshop, 9 St Edward’s Passage, Cambridge, UK',
    desc: 'Wander back into the centre for the tiny, creaking Haunted Bookshop on St Edward’s Passage — second-hand and antiquarian books stacked to the rafters, plus a resident ghost (a white lady, allegedly). Then browse the stalls on Market Square.',
    tips: [
      'Buy each other a book without showing which one — swap them at dinner. Instant tradition.',
      'The shop is genuinely tiny; it usually closes around 17:00-17:30, so make it your first stop after punting.',
      'Market Square has fudge, prints and vintage stalls — perfect low-effort souvenir hunting.',
    ],
  },
  {
    id: 'eagle',
    tease: 'a pint where DNA was announced',
    walkLine: 'two minutes to a historic pint',
    nowLine: 'look up in the RAF bar',
    place: 'The Eagle',
    emoji: '🍺',
    name: 'A pint at The Eagle',
    start: '17:30', end: '18:30',
    walk: '2 min walk',
    booked: false,
    mapQuery: 'The Eagle, 8 Bene’t Street, Cambridge, UK',
    desc: 'Cambridge’s most storied pub. In 1953 Crick and Watson burst in here and announced they’d discovered “the secret of life” — the structure of DNA. The ceiling of the RAF Bar still carries graffiti burned by WWII airmen.',
    tips: [
      'Order the “Eagle’s DNA” ale and find the DNA blue plaque outside.',
      'Look up in the RAF Bar — squadron numbers scorched into the ceiling with candles and lighters.',
      'The courtyard is lovely if the evening is warm.',
    ],
  },
  {
    id: 'dishoom',
    tease: 'black daal and Bombay comfort',
    walkLine: 'name on the list, then drinks at the bar',
    nowLine: 'order the black daal — trust us',
    place: 'Permit Room',
    emoji: '🍛',
    name: 'Dinner at Permit Room (Dishoom)',
    start: '18:30', end: '20:00',
    walk: '4 min walk',
    booked: false,
    mapQuery: 'Dishoom Permit Room, 17 Trinity Street, Cambridge, UK',
    website: 'https://www.permitroom.co.uk/locations/cambridge/',
    desc: 'Dishoom’s Bombay bar-café on Trinity Street. Walk-ins only for two — put your name down, grab a drink at the bar, and let the evening slow down.',
    tips: [
      'Put your name on the list the moment you arrive, then order a drink — the wait is part of the fun.',
      'Order the house black daal (24 hours in the making), chicken ruby and garlic naan.',
      'Drinks-wise: a “Permit Room Lager” or one of the colabas/sodas if you’re pacing yourselves.',
      'If the wait is silly, plan B: Bedouin, Aromi or The Senate are all close.',
    ],
  },
  {
    id: 'gelato',
    tease: 'the grand finale',
    walkLine: 'one last stroll — dessert is earned',
    nowLine: 'one classic flavour, one weird one',
    place: 'Jack’s Gelato',
    emoji: '🍨',
    name: 'Jack’s Gelato — grand finale',
    start: '20:00', end: '20:30',
    walk: '4 min walk',
    booked: false,
    mapQuery: 'Jack’s Gelato, 6 Bene’t Street, Cambridge, UK',
    website: 'https://www.jacksgelato.com',
    desc: 'The perfect ending. Jack’s hand-makes small batches daily — the flavour board changes every day. Take your cones down King’s Parade for one last golden-hour look at the chapel.',
    tips: [
      'The queue moves fast and is always worth it.',
      'Rule of the house: one classic flavour, one weird one (dark chocolate & sea salt + whatever sounds wrong).',
      'Eat them on the wall opposite King’s — the chapel at dusk is the closing shot of the film.',
    ],
  },
];
